/* auto-generated by optimize_menu.py */
const VERSION = 'menu-80d19d1b3e';
const IMG_CACHE = 'img-v3';

const ICONS_PREFIX  = '/icons';
const IMAGES_PREFIX = '/images';

// ==== SW: динамический кеш для изображений ====


self.addEventListener('install', (e) => {
  self.skipWaiting();
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    (async () => {
      const keys = await caches.keys();
      await Promise.all(keys.filter(k => k !== IMG_CACHE).map(k => caches.delete(k)));
      await self.clients.claim();
    })()
  );
});

self.addEventListener('fetch', (e) => {
  const req = e.request;
  const url = new URL(req.url);
  const isImage = req.destination === 'image' || url.pathname.startsWith('/images/');

  if (!isImage) return; // не перехватываем прочие запросы

  e.respondWith((async () => {
    const cache = await caches.open(IMG_CACHE);

    const cached = await cache.match(req, { ignoreVary: true });
    if (cached) return cached;

    try {
      const net = await fetch(req, { cache: 'no-store' });
      if (net.ok) cache.put(req, net.clone());
      return net;
    } catch {
      // если сеть упала, а в кеше пусто — стандартная ошибка
      return cached || Response.error();
    }
  })());
});

