/* auto-generated by optimize_menu.py */
const VERSION = 'menu-80d19d1b3e';
const CACHE = 'static-' + VERSION;
const PRECACHE = [
  "/icons/12242716.png",
  "/icons/12344194.png",
  "/icons/12367886.png",
  "/icons/1256449.png",
  "/icons/13850681.png",
  "/icons/13b01a3ed103ff17233aa8dcca6d5313-vegetarian-round-green-badge.webp",
  "/icons/2224196.png",
  "/icons/2435673 1.png",
  "/icons/2435673.png",
  "/icons/299-2997107_pere-magloire-vs-calvados-calvados-pere-magloire.png",
  "/icons/3944096.png",
  "/icons/5036926.png",
  "/icons/5346247.png",
  "/icons/5821504.png",
  "/icons/6692378.png",
  "/icons/6773707.png",
  "/icons/6786878.png",
  "/icons/7013845.png",
  "/icons/9410695.png",
  "/icons/99-997123_jpg-black-and-white-library-italian-cuisine-pizza.png",
  "/icons/ChatGPT_Image_14.png",
  "/icons/fire-57.png",
  "/icons/image 1.png",
  "/icons/image 2.png",
  "/icons/image 3.png",
  "/icons/image.png",
  "/icons/images_(21).jpeg",
  "/icons/kunz.png",
  "/icons/pngtree-raw-food-label-png-png-image_5940210.png",
  "/icons/steak-doneness-chart-differently-cooked-pieces-vector-9416721.jpg",
  "/icons/wine.png",
  "/images/0b2acab1-fea9-4d6f-99e7-f711b3f492bd.png",
  "/images/1.jpg",
  "/images/10683956.jpg",
  "/images/12__100____490_.jpg",
  "/images/155cc1dd-f91e-4fee-8526-1ebfed98c1b3.png",
  "/images/1715d5874004a3d661a55e24118d90f8_1000_1000_90.webp",
  "/images/1______210__880_.jpg",
  "/images/2.jpg",
  "/images/2025-06-30_23-18-59.png",
  "/images/2025-07-01_00-07-18.png",
  "/images/2025-07-01_00-59-32.png",
  "/images/2025-07-01_01-05-58.png",
  "/images/2025-07-01_01-13-58.png",
  "/images/2025-07-01_01-14-26.png",
  "/images/2025-07-01_01-15-21.png",
  "/images/2025-07-01_01-17-03.png",
  "/images/2025-07-04_22-50-40.png",
  "/images/2025-07-05_10-24-52.png",
  "/images/2025-07-05_10-25-40.png",
  "/images/2025-07-05_10-26-25.png",
  "/images/2025-07-05_10-27-10.png",
  "/images/2025-07-05_10-27-39.png",
  "/images/2025-07-05_10-28-20.png",
  "/images/2025-07-05_13-05-35.png",
  "/images/2025-07-08_13-40-17.png",
  "/images/2025-07-08_13-56-58.png",
  "/images/2025-07-08_14-42-43.png",
  "/images/2025-07-08_14-55-05.png",
  "/images/2025-07-08_14-58-48.png",
  "/images/2025-07-08_15-35-44.png",
  "/images/2198d8f8-2d7f-46cd-93c6-0a6826476ce8.png",
  "/images/25822262.jpg",
  "/images/29265842.jpg",
  "/images/2_1__100____770_.jpg",
  "/images/2______375__1380_.jpg",
  "/images/2bfe793a-a68e-4790-b707-44395f411174.png",
  "/images/3.jpg",
  "/images/33451393.jpg",
  "/images/33___100____1440_.jpg",
  "/images/398e5cfa-3101-4d5a-b68b-8597f74c84b7.png",
  "/images/4.jpg",
  "/images/41___1770_.jpg",
  "/images/41______320___1480_.jpg",
  "/images/42__100____2550_.jpg",
  "/images/5.jpg",
  "/images/53__100____920_.jpg",
  "/images/53___770__2.jpg",
  "/images/60662643.jpg",
  "/images/68935022.jpg",
  "/images/6_100____990_.jpg",
  "/images/72__100____870_.jpg",
  "/images/7___1880_.jpg",
  "/images/82__100___1200_.jpg",
  "/images/8_-_2320_.jpg",
  "/images/92033367.jpg",
  "/images/92245071.jpg",
  "/images/99290880.jpg",
  "/images/DSC09344.jpg",
  "/images/DSC09469.jpg",
  "/images/Fetuchini.jpg",
  "/images/IMG_7444.jpg",
  "/images/IMG_8165.jpg",
  "/images/Photo0076.jpg",
  "/images/Photo0100.jpg",
  "/images/Photo0108.jpg",
  "/images/Photo0116.jpg",
  "/images/Photo0125.jpg",
  "/images/Rizotto.jpg",
  "/images/Sabor_De_La_Vida_280.jpg",
  "/images/Sabor_De_La_Vida_280_(1).jpg",
  "/images/Sabor_De_La_Vida_280_(2).jpg",
  "/images/Sabor_De_La_Vida_280_(3).jpg",
  "/images/Sabor_De_La_Vida_280_(4).jpg",
  "/images/Sabor_De_La_Vida_280_(5).jpg",
  "/images/WhatsApp_Image_2022-.jpeg",
  "/images/_ 1.jpg",
  "/images/_.jpg",
  "/images/_1600x1200_(1).jpg",
  "/images/_1600x1200_(2).jpg",
  "/images/_1600x1200_(3).jpg",
  "/images/_1600x1200_(4).jpg",
  "/images/_1600x1200_(5).jpg",
  "/images/_1600x1200_(6).jpg",
  "/images/_1_(1).jpg",
  "/images/_2.jpg",
  "/images/_DSC7043.jpg",
  "/images/_DSC7314.jpg",
  "/images/_DSC7330.jpg",
  "/images/_DSC7359.jpg",
  "/images/_DSC7365.jpg",
  "/images/_DSC7445.jpg",
  "/images/__-_7.jpg",
  "/images/__4_2.jpg",
  "/images/__7.jpg",
  "/images/___1.jpg",
  "/images/____2.jpg",
  "/images/_____8.jpg",
  "/images/bcb59dbc-d346-4c84-83b6-0a6de2961dad.png",
  "/images/bfa7bb30-a2e9-4049-b0b1-8140a941e133.png",
  "/images/c440d179-7120-4ddf-8d23-1b75ca85a8d8.png",
  "/images/dc6a1317-5381-4633-85d7-9ac4e1e64a9e.png",
  "/images/dd9177e7-bf85-4104-887c-310f25d062d2.png",
  "/images/f751fe1f-ef60-4a98-a028-be3113d84654.png",
  "/images/noroot.jpg",
  "/images/noroot.png"
];
const ICONS_PREFIX  = '/icons';
const IMAGES_PREFIX = '/images';

self.addEventListener('install', event => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    await cache.addAll(PRECACHE);
    self.skipWaiting();
  })());
});

self.addEventListener('activate', event => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k)));
    self.clients.claim();
  })());
});

self.addEventListener('fetch', event => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== location.origin) return;
  const p = url.pathname;
  if (!(p.startsWith(ICONS_PREFIX) || p.startsWith(IMAGES_PREFIX))) return;

  event.respondWith((async () => {
    const cache = await caches.open(CACHE);
    const cached = await cache.match(req);
    if (cached) return cached;
    const resp = await fetch(req);
    if (resp && resp.ok) cache.put(req, resp.clone());
    return resp;
  })());
});
